### ISSUE TITLE
NameError: global name 'mode_verify' is not defined

### ISSUE THREAD

**Issue by ShaneKent** [atc1441/chflasher#5]
I've been running into a very strange situation when using this chflasher.exe to flash a CH559.  It seems like any time I try to call a `memset` or `memcpy` or similar function that I come across this error:

```
packihx: read 373 lines, wrote 724: OK.
hex2bin v1.0.1, Copyright (C) 1999 Jacques Pelletier
Lowest address = 00000000
Highest address = 00002C6D
Found CH559
Bootloader version: 2.40
Flash Erased
Filesize: 11374 bytes
Writing success
Traceback (most recent call last):
  File "chflasher.py", line 228, in <module>
  File "chflasher.py", line 208, in writefilev2
NameError: global name 'mode_verify' is not defined
[17208] Failed to execute script chflasher
```

The binary is created correctly, but flashing process fails at the verify step. The binary is loaded properly without issue if I instead utilize the WCHISPTool to flash via Serial or USB connection.

**Comment by ShaneKent** [comment]
I took the `chflasher.py` file in this repository and put it into my working directory. Doing that changed the error to this:
```
packihx: read 373 lines, wrote 725: OK.
hex2bin v1.0.1, Copyright (C) 1999 Jacques Pelletier
Lowest address = 00000000
Highest address = 00002C74
Found CH559
Bootloader version: 2.40
Flash Erased
Filesize: 11381 bytes
Writing success
Traceback (most recent call last):
  File "chflasher.py", line 228, in <module>
    elif mode == mode_verify_v2:
  File "chflasher.py", line 208, in writefilev2
    outbuffer[1] = (pkt_length+5)
NameError: global name 'mode_verify' is not defined
[15064] Failed to execute script chflasher
```

Perhaps this will add some more clarity on the issue.

**Comment by nockieboy** [comment]
*gentle prod*  I'm also experiencing this problem in the same (or similar) circumstances whilst compiling and flashing code to a CH559.

From my very basic testing, I'm wondering if it's a file size issue?  My code compiles with no issues with a reported file size of 11212 bytes.  If I replace a 'DEBUG_OUT' command in USBHost.c (for example) with a 'printf' command, the file size goes up to 11303 and I get the reported errors:

```
packihx: read 369 lines, wrote 720: OK.
hex2bin v1.0.1, Copyright (C) 1999 Jacques Pelletier
Lowest address = 00000000
Highest address = 00002C26
Found CH559
Bootloader version: 2.31
Flash Erased
Filesize: 11303 bytes
Writing success
Traceback (most recent call last):
  File "chflasher.py", line 228, in <module>
  File "chflasher.py", line 208, in writefilev2
NameError: global name 'mode_verify' is not defined
[13088] Failed to execute script chflasher
```
I've tested and tested, and it seems a file size of up to 11267 bytes is fine, but 11268 (or more) causes the error.  I've tested this by simply printing a string to serial using printf and increasing the size of the string until I found the cutoff between a successful compile and a failed one with the above error.

**Comment by nockieboy** [comment]
*gentle prod*  I'm also experiencing this problem in the same (or similar) circumstances whilst compiling and flashing code to a CH559.

From my very basic testing, I'm wondering if it's a file size issue?  My code compiles with no issues with a reported file size of 11212 bytes.  If I replace a 'DEBUG_OUT' command in USBHost.c (for example) with a 'printf' command, the file size goes up to 11303 and I get the reported errors:

```
packihx: read 369 lines, wrote 720: OK.
hex2bin v1.0.1, Copyright (C) 1999 Jacques Pelletier
Lowest address = 00000000
Highest address = 00002C26
Found CH559
Bootloader version: 2.31
Flash Erased
Filesize: 11303 bytes
Writing success
Traceback (most recent call last):
  File "chflasher.py", line 228, in <module>
  File "chflasher.py", line 208, in writefilev2
NameError: global name 'mode_verify' is not defined
[13088] Failed to execute script chflasher
```
I've tested and tested, and it seems a file size of 11267 bytes is fine, but 11268 causes the error.  I've tested this by simply printing a string to serial using printf and increasing the size of the string until I found the cutoff between a successful compile and a failed one with the above error.

**Comment by bbbbbr** [comment]
Find the `erase_size` variables and increase them from 11 (presumably 11 x 1024 bytes) to a higher value.

You can see in this other project where they're passing a value as high as 60, so it can probably go up to the full flash size of 64. That may cause the erase cycle to take longer.
https://github.com/toyoshim/ch559flasher/blob/b9f1e8834914b5c58ffec7f1f305955466a5c701/src/ch559.rs#L110
